_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 2
                - 3
                - 41
                - 55
            "2":
                - 1
                - 2
                - 3
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.2
            "8":
                - 3
                - 5
            "12": 0.18.2
            "13": windows-amd64
distill:
    value: simkd_mp
epochs:
    value: 240
learning_rate:
    value: 0.001
mp_ratio:
    value: 0.6666666666666666
student_architecture:
    value: MobileNetV2_1_0
teacher_architecture:
    value: resnet32x4
trial:
    value: "2"
